version: '3'

services:
  app:
    build:
      context: .
      dockerfile: ./docker/app/Dockerfile
    volumes:
      - ./src:/src
      - node_modules:/src/node_modules
    env_file: ./.env
    command: sh -c "node index.js"
    tty: true
    stdin_open: true

volumes:
  node_modules:
    driver: local